// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuUYGdt-5fh_uq8iHgHUnuDO12j8FucLs',
    appId: '1:593161257656:web:c80e329933e8caa2852a4d',
    messagingSenderId: '593161257656',
    projectId: 'tfg-controlhorario',
    authDomain: 'tfg-controlhorario.firebaseapp.com',
    storageBucket: 'tfg-controlhorario.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq3HvQAVY5spnFjOwD_mT_9NXpLvgdQ4M',
    appId: '1:593161257656:android:db7ba208220732d3852a4d',
    messagingSenderId: '593161257656',
    projectId: 'tfg-controlhorario',
    storageBucket: 'tfg-controlhorario.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFK39BewXNzl8fCxXPNDo7Ssm6Az7TpzY',
    appId: '1:593161257656:ios:c0254561ad9da62f852a4d',
    messagingSenderId: '593161257656',
    projectId: 'tfg-controlhorario',
    storageBucket: 'tfg-controlhorario.firebasestorage.app',
    iosBundleId: 'com.example.tfgApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFK39BewXNzl8fCxXPNDo7Ssm6Az7TpzY',
    appId: '1:593161257656:ios:c0254561ad9da62f852a4d',
    messagingSenderId: '593161257656',
    projectId: 'tfg-controlhorario',
    storageBucket: 'tfg-controlhorario.firebasestorage.app',
    iosBundleId: 'com.example.tfgApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuUYGdt-5fh_uq8iHgHUnuDO12j8FucLs',
    appId: '1:593161257656:web:1283068392280d26852a4d',
    messagingSenderId: '593161257656',
    projectId: 'tfg-controlhorario',
    authDomain: 'tfg-controlhorario.firebaseapp.com',
    storageBucket: 'tfg-controlhorario.firebasestorage.app',
  );

}